# Copyright The SimpleKernel Contributors

[package]
name = "per_cpu"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Per-CPU data infrastructure — #[cpu_local] declaration, CpuLocal<T> access, percpu_init"
edition.workspace = true

[dependencies]
macros = { path = "../macros" }
config = { path = "../config" }
arch = { path = "../arch" }

[lints]
workspace = true
