var dir_9792f77b7388247cc984bf8bf02ef530 =
[
    [ "affinity_test.cpp", "affinity__test_8cpp.html", "affinity__test_8cpp" ],
    [ "balance_test.cpp", "system__test_2balance__test_8cpp.html", "system__test_2balance__test_8cpp" ],
    [ "cfs_scheduler_test.cpp", "system__test_2cfs__scheduler__test_8cpp.html", "system__test_2cfs__scheduler__test_8cpp" ],
    [ "clone_test.cpp", "clone__test_8cpp.html", "clone__test_8cpp" ],
    [ "cross_core_test.cpp", "cross__core__test_8cpp.html", "cross__core__test_8cpp" ],
    [ "ctor_dtor_test.cpp", "ctor__dtor__test_8cpp.html", "ctor__dtor__test_8cpp" ],
    [ "exit_test.cpp", "exit__test_8cpp.html", "exit__test_8cpp" ],
    [ "fatfs_test.cpp", "fatfs__test_8cpp.html", "fatfs__test_8cpp" ],
    [ "fifo_scheduler_test.cpp", "system__test_2fifo__scheduler__test_8cpp.html", "system__test_2fifo__scheduler__test_8cpp" ],
    [ "fork_test.cpp", "fork__test_8cpp.html", "fork__test_8cpp" ],
    [ "interrupt_test.cpp", "interrupt__test_8cpp.html", "interrupt__test_8cpp" ],
    [ "ipi_test.cpp", "ipi__test_8cpp.html", "ipi__test_8cpp" ],
    [ "kernel_task_test.cpp", "kernel__task__test_8cpp.html", "kernel__task__test_8cpp" ],
    [ "main.cpp", "tests_2system__test_2main_8cpp.html", "tests_2system__test_2main_8cpp" ],
    [ "memory_test.cpp", "memory__test_8cpp.html", "memory__test_8cpp" ],
    [ "mutex_test.cpp", "mutex__test_8cpp.html", "mutex__test_8cpp" ],
    [ "ramfs_test.cpp", "system__test_2ramfs__test_8cpp.html", "system__test_2ramfs__test_8cpp" ],
    [ "rr_scheduler_test.cpp", "system__test_2rr__scheduler__test_8cpp.html", "system__test_2rr__scheduler__test_8cpp" ],
    [ "signal_test.cpp", "signal__test_8cpp.html", "signal__test_8cpp" ],
    [ "spinlock_test.cpp", "system__test_2spinlock__test_8cpp.html", "system__test_2spinlock__test_8cpp" ],
    [ "stress_test.cpp", "stress__test_8cpp.html", "stress__test_8cpp" ],
    [ "system_test.h", "system__test_8h.html", "system__test_8h" ],
    [ "thread_group_test.cpp", "thread__group__test_8cpp.html", "thread__group__test_8cpp" ],
    [ "tick_test.cpp", "tick__test_8cpp.html", "tick__test_8cpp" ],
    [ "user_task_test.cpp", "user__task__test_8cpp.html", "user__task__test_8cpp" ],
    [ "virtual_memory_test.cpp", "system__test_2virtual__memory__test_8cpp.html", "system__test_2virtual__memory__test_8cpp" ],
    [ "wait_test.cpp", "wait__test_8cpp.html", "wait__test_8cpp" ],
    [ "yield_test.cpp", "yield__test_8cpp.html", "yield__test_8cpp" ],
    [ "zombie_reap_test.cpp", "zombie__reap__test_8cpp.html", "zombie__reap__test_8cpp" ]
];