# Copyright The SimpleKernel Contributors

[package]
name = "device-test"
description = "验证 DeviceManager 枚举和 VirtIO 块设备读取"
edition.workspace = true

[[bin]]
name = "device-test"
test = false

[dependencies]
test_harness = { path = "../test_harness" }
simplekernel = { path = "../..", default-features = false }
log.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true

[lints]
workspace = true
