[package]
name = "frame_allocator"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Physical frame allocator with RAII ownership tracking"
edition.workspace = true

[dependencies]
memory_types = { path = "../memory_types" }
sync_crate = { path = "../sync", package = "sync" }

buddy_system_allocator.workspace = true
heapless.workspace = true
log.workspace = true

[lints]
workspace = true
