[package]
name = "paging-table-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "paging-table-test"
path = "src/main.rs"
test = false
bench = false

[dependencies]
test_harness = { path = "../../../crates/test_harness" }
simplekernel = { path = "../../..", default-features = false }
paging = { path = "../../../crates/paging" }
memory_types = { path = "../../../crates/memory_types" }
config = { path = "../../../crates/config" }
log.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true

[lints]
workspace = true
