[package]
name = "paging-test"
description = "页表参数、权限管理及边界 panic 测试"
edition.workspace = true

[[bin]]
name = "basic"
path = "src/basic.rs"
test = false

[[bin]]
name = "table"
path = "src/table.rs"
test = false

[[bin]]
name = "mapping"
path = "src/mapping.rs"
test = false

[[bin]]
name = "conflict-panic"
path = "src/conflict_panic.rs"
test = false

[[bin]]
name = "equal-range-panic"
path = "src/equal_range_panic.rs"
test = false

[[bin]]
name = "reversed-range-panic"
path = "src/reversed_range_panic.rs"
test = false

[dependencies]
test_harness = { path = "../test_harness" }
simplekernel = { path = "../..", default-features = false }
paging = { path = "../../crates/paging" }
frame_allocator = { path = "../../crates/frame_allocator" }
memory_types = { path = "../../crates/memory_types" }
config = { path = "../../crates/config" }
log.workspace = true
heapless.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true

[lints]
workspace = true
