[package]
name = "memory_types"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Type-safe physical/virtual address, page frame, and page size abstractions for SimpleKernel"
edition.workspace = true

[dependencies]
config = { path = "../config" }
span = { path = "../span" }

[lints]
workspace = true
