[package]
name = "boot-info"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
address = { path = "../address" }
spin = { version = "0.9", default-features = false, features = ["once"] }
