[package]
name = "heap"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Interrupt-safe kernel heap allocator (#[global_allocator])"
edition.workspace = true

[dependencies]
config = { path = "../config" }
sync_crate = { path = "../sync", package = "sync" }

buddy_system_allocator.workspace = true
log.workspace = true
