/**
 * @copyright Copyright The SimpleKernel Contributors
 */

#ifndef SIMPLEKERNEL_SRC_DEVICE_VIRTIO_DEVICE_VIRTIO_CONSOLE_H_
#define SIMPLEKERNEL_SRC_DEVICE_VIRTIO_DEVICE_VIRTIO_CONSOLE_H_

#endif  // SIMPLEKERNEL_SRC_DEVICE_VIRTIO_DEVICE_VIRTIO_CONSOLE_H_
