[package]
name = "per-cpu"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
macros = { path = "../macros" }
config = { path = "../config" }
spin = { version = "0.9", default-features = false, features = ["once"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "9"
tock-registers = "0.9"
