[package]
name = "macros"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macros for SimpleKernel (#[cpu_local], etc.)"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
