[package]
name = "macros"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macros for SimpleKernel (#[cpu_local], etc.)"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
