[package]
name = "test_harness"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Test harness for standalone QEMU test binaries"

[dependencies]
simplekernel = { path = "../../", default-features = false }
per_cpu = { path = "../per_cpu" }
heap = { path = "../heap" }
memory = { path = "../memory" }
config = { path = "../config" }
heapless.workspace = true
log.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true

[lints]
workspace = true
