# Copyright The SimpleKernel Contributors

[package]
name = "paging"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Page table management"
edition.workspace = true

[dependencies]
arch = { path = "../arch" }
config = { path = "../config" }
memory_types = { path = "../memory_types" }
page_table_entry = { path = "../page_table_entry" }
frame_allocator = { path = "../frame_allocator" }
sync_crate = { path = "../sync", package = "sync" }
tlb = { path = "../tlb" }
log.workspace = true
spin.workspace = true

[lints]
workspace = true
