[package]
name = "arch-test"
description = "验证架构相关基础能力"
edition.workspace = true

[[bin]]
name = "arch-test"
test = false

[dependencies]
test_harness = { path = "../test_harness" }
simplekernel = { path = "../..", default-features = false }
config = { path = "../../crates/config" }
log.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true

[lints]
workspace = true
