[package]
name = "heap-test"
description = "验证堆分配（Box、Vec、大块）"
edition.workspace = true

[[bin]]
name = "heap-test"
test = false

[dependencies]
test_harness = { path = "../test_harness" }
simplekernel = { path = "../..", default-features = false }
log.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true

[lints]
workspace = true
