# Copyright The SimpleKernel Contributors

[package]
name = "sync-test"
description = "SpinLock、LockStack 及边界 panic 测试"
edition.workspace = true

[[bin]]
name = "spinlock"
path = "src/spinlock.rs"
test = false

[[bin]]
name = "lockstack"
path = "src/lockstack.rs"
test = false

[[bin]]
name = "lockstack-pop-mismatch-panic"
path = "src/lockstack_pop_mismatch_panic.rs"
test = false

[[bin]]
name = "recursive-lock-panic"
path = "src/recursive_lock_panic.rs"
test = false

[dependencies]
test_harness = { path = "../test_harness" }
simplekernel = { path = "../..", default-features = false }
sync = { path = "../../crates/sync" }
log.workspace = true
heapless.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true

[lints]
workspace = true
