# Copyright The SimpleKernel Contributors

[package]
name = "memory"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
config = { path = "../config" }
memory_types = { path = "../memory_types" }
per_cpu = { path = "../per_cpu" }
paging = { path = "../paging" }
tlb = { path = "../tlb" }
frame_allocator = { path = "../frame_allocator" }
heap_crate = { path = "../heap", package = "heap" }
platform_fdt = { path = "../platform_fdt" }

log.workspace = true
spin.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
