[package]
name = "memory"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
config = { path = "../config" }
memory_types = { path = "../memory_types" }
sync_crate = { path = "../sync", package = "sync" }
per_cpu = { path = "../per_cpu" }
paging = { path = "../paging" }
frame_allocator = { path = "../frame_allocator" }
heap_crate = { path = "../heap", package = "heap" }
tlb = { path = "../tlb" }

bitflags.workspace = true
zerocopy.workspace = true
log.workspace = true
spin.workspace = true

[dev-dependencies]
paging = { path = "../paging", features = ["test-support"] }
frame_allocator = { path = "../frame_allocator", features = ["test-support"] }

[lints]
workspace = true
